version: '3.8'

services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    volumes:
      - ./headscale/config:/etc/headscale
      - ./headscale/data:/var/lib/headscale
    ports:
      - "8080:8080"
    command: headscale serve
    restart: unless-stopped

  dashboard:
    build:
      context: ./agp-dashboard-web
      dockerfile: Dockerfile
    container_name: agp_dashboard
    ports:
      - "5000:5000"
    volumes:
      - ./agp-dashboard-web:/app
    restart: unless-stopped
    depends_on:
      - headscale
