"""Add Project table

Revision ID: 326943c795c8
Revises: dda39e0eafab
Create Date: 2025-10-10 13:59:49.977270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326943c795c8'
down_revision = 'dda39e0eafab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # The user_agent_association table also seems to be a legitimate missing table, so we keep its creation.
    op.create_table('user_agent_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # All other auto-detected changes have been removed to prevent data loss.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_agent_association')
    op.drop_table('project')
    # ### end Alembic commands ###