"""Add status to ThreeDModel

Revision ID: 85e5d1ba99d7
Revises: 5f708d7d29b8
Create Date: 2025-09-30 13:51:01.500240

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85e5d1ba99d7"
down_revision = "5f708d7d29b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("three_d_model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("three_d_model", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
