"""Add Setting model

Revision ID: d03a1f3d623e
Revises: 298e14858a52
Create Date: 2025-09-28 12:32:33.134023

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d03a1f3d623e"
down_revision = "298e14858a52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("setting", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_setting_key"), ["key"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("setting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_setting_key"))

    op.drop_table("setting")
    # ### end Alembic commands ###
